# Generated by Django 4.1.2 on 2022-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '*'), (2, '* *'), (3, '* * *'), (4, '* * * *'), (5, '* * * * *')], default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
