# Generated by Django 4.1.2 on 2022-11-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_review_stars_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1),
        ),
    ]
